INSERT INTO `loc_countries` (`id`, `code`, `alpha_3`, `name`, `name_de`, `name_fr`, `name_it`) VALUES
(4, 'AF', 'AFG', 'Afghanistan', 'Afghanistan', 'Afghanistan', 'Afghanistan'),
(818, 'EG', 'EGY', 'Egypt', 'Ägypten', 'Égypte', 'Egitto'),
(248, 'AX', 'ALA', 'Åland Islands', 'Åland', 'Îles Åland', 'Isole Åland'),
(8, 'AL', 'ALB', 'Albania', 'Albanien', 'Albanie', 'Albania'),
(12, 'DZ', 'DZA', 'Algeria', 'Algerien', 'Algérie', 'Algeria'),
(16, 'AS', 'ASM', 'American Samoa', 'Amerikanisch-Samoa', 'Samoa américaines', 'Samoa Americane'),
(850, 'VI', 'VIR', 'Virgin Islands (U.S.)', 'Amerikanische Jungferninseln', 'Îles Vierges des États-Unis', 'Isole Vergini americane'),
(20, 'AD', 'AND', 'Andorra', 'Andorra', 'Andorre', 'Andorra'),
(24, 'AO', 'AGO', 'Angola', 'Angola', 'Angola', 'Angola'),
(660, 'AI', 'AIA', 'Anguilla', 'Anguilla', 'Anguilla', 'Anguilla'),
(10, 'AQ', 'ATA', 'Antarctica', 'Antarktika (Sonderstatus durch Antarktis-Vertrag)', 'Antarctique', 'Antartide'),
(28, 'AG', 'ATG', 'Antigua and Barbuda', 'Antigua und Barbuda', 'Antigua-et-Barbuda', 'Antigua e Barbuda'),
(226, 'GQ', 'GNQ', 'Equatorial Guinea', 'Äquatorialguinea', 'Guinée équatoriale', 'Guinea Equatoriale'),
(32, 'AR', 'ARG', 'Argentina', 'Argentinien', 'Argentine', 'Argentina'),
(51, 'AM', 'ARM', 'Armenia', 'Armenien', 'Arménie', 'Armenia'),
(533, 'AW', 'ABW', 'Aruba', 'Aruba', 'Aruba', 'Aruba'),
(31, 'AZ', 'AZE', 'Azerbaijan', 'Aserbaidschan', 'Azerbaïdjan', 'Azerbaigian'),
(231, 'ET', 'ETH', 'Ethiopia', 'Äthiopien', 'Éthiopie', 'Etiopia'),
(36, 'AU', 'AUS', 'Australia', 'Australien', 'Australie', 'Australia'),
(44, 'BS', 'BHS', 'Bahamas', 'Bahamas', 'Bahamas', 'Bahamas'),
(48, 'BH', 'BHR', 'Bahrain', 'Bahrain', 'Bahreïn', 'Bahrein'),
(50, 'BD', 'BGD', 'Bangladesh', 'Bangladesch', 'Bangladesh', 'Bangladesh'),
(52, 'BB', 'BRB', 'Barbados', 'Barbados', 'Barbade', 'Barbados'),
(112, 'BY', 'BLR', 'Belarus', 'Belarus (Weißrussland)', 'Biélorussie', 'Bielorussia'),
(56, 'BE', 'BEL', 'Belgium', 'Belgien', 'Belgique', 'Belgio'),
(84, 'BZ', 'BLZ', 'Belize', 'Belize', 'Belize', 'Belize'),
(204, 'BJ', 'BEN', 'Benin', 'Benin', 'Bénin', 'Benin'),
(60, 'BM', 'BMU', 'Bermuda', 'Bermuda', 'Bermudes', 'Bermuda'),
(64, 'BT', 'BTN', 'Bhutan', 'Bhutan', 'Bhoutan', 'Bhutan'),
(68, 'BO', 'BOL', 'Bolivia (Plurinational State of)', 'Bolivien', 'Bolivie', 'Bolivia'),
(535, 'BQ', 'BES', 'Bonaire, Sint Eustatius and Saba', 'Bonaire, Sint Eustatius und Saba (Niederlande)', 'Pays-Bas caribéens', 'Isole BES'),
(70, 'BA', 'BIH', 'Bosnia and Herzegovina', 'Bosnien und Herzegowina', 'Bosnie-Herzégovine', 'Bosnia ed Erzegovina'),
(72, 'BW', 'BWA', 'Botswana', 'Botswana', 'Botswana', 'Botswana'),
(74, 'BV', 'BVT', 'Bouvet Island', 'Bouvetinsel', 'Île Bouvet', 'Isola Bouvet'),
(76, 'BR', 'BRA', 'Brazil', 'Brasilien', 'Brésil', 'Brasile'),
(92, 'VG', 'VGB', 'Virgin Islands (British)', 'Britische Jungferninseln', 'Îles Vierges britanniques', 'Isole Vergini britanniche'),
(86, 'IO', 'IOT', 'British Indian Ocean Territory', 'Britisches Territorium im Indischen Ozean', 'Territoire britannique de l\'océan Indien', 'Territorio britannico dell\'Oceano Indiano'),
(96, 'BN', 'BRN', 'Brunei Darussalam', 'Brunei Darussalam', 'Brunei', 'Brunei'),
(100, 'BG', 'BGR', 'Bulgaria', 'Bulgarien', 'Bulgarie', 'Bulgaria'),
(854, 'BF', 'BFA', 'Burkina Faso', 'Burkina Faso', 'Burkina Faso', 'Burkina Faso'),
(108, 'BI', 'BDI', 'Burundi', 'Burundi', 'Burundi', 'Burundi'),
(152, 'CL', 'CHL', 'Chile', 'Chile', 'Chili', 'Cile'),
(156, 'CN', 'CHN', 'China', 'China', 'Chine', 'Cina'),
(184, 'CK', 'COK', 'Cook Islands', 'Cookinseln', 'Îles Cook', 'Isole Cook'),
(188, 'CR', 'CRI', 'Costa Rica', 'Costa Rica', 'Costa Rica', 'Costa Rica'),
(384, 'CI', 'CIV', 'Ivory Coast\n', 'Côte d’Ivoire (Elfenbeinküste)', 'Côte d\'Ivoire', 'Costa d\'Avorio'),
(531, 'CW', 'CUW', 'Curaçao', 'Curaçao', 'Curaçao', 'Curaçao'),
(208, 'DK', 'DNK', 'Denmark', 'Dänemark', 'Danemark', 'Danimarca'),
(276, 'DE', 'DEU', 'Germany', 'Deutschland', 'Allemagne', 'Germania'),
(212, 'DM', 'DMA', 'Dominica', 'Dominica', 'Dominique', 'Dominica'),
(214, 'DO', 'DOM', 'Dominican Republic', 'Dominikanische Republik', 'République dominicaine', 'Rep. Dominicana'),
(262, 'DJ', 'DJI', 'Djibouti', 'Dschibuti', 'Djibouti', 'Gibuti'),
(218, 'EC', 'ECU', 'Ecuador', 'Ecuador', 'Équateur (pays)', 'Ecuador'),
(222, 'SV', 'SLV', 'El Salvador', 'El Salvador', 'Salvador', 'El Salvador'),
(232, 'ER', 'ERI', 'Eritrea', 'Eritrea', 'Érythrée', 'Eritrea'),
(233, 'EE', 'EST', 'Estonia', 'Estland', 'Estonie', 'Estonia'),
(238, 'FK', 'FLK', 'Falkland Islands (Malvinas)', 'Falklandinseln', 'Malouines', 'Isole Falkland'),
(234, 'FO', 'FRO', 'Faroe Islands', 'Färöer', 'Îles Féroé', 'Fær Øer'),
(242, 'FJ', 'FJI', 'Fiji', 'Fidschi', 'Fidji', 'Figi'),
(246, 'FI', 'FIN', 'Finland', 'Finnland', 'Finlande', 'Finlandia'),
(250, 'FR', 'FRA', 'France', 'Frankreich', 'France', 'Francia'),
(254, 'GF', 'GUF', 'French Guiana', 'Französisch-Guayana', 'Guyane', 'Guyana francese'),
(258, 'PF', 'PYF', 'French Polynesia', 'Französisch-Polynesien', 'Polynésie française', 'Polinesia Francese'),
(260, 'TF', 'ATF', 'French Southern Territories', 'Französische Süd- und Antarktisgebiete', 'Terres australes et antarctiques françaises', 'Terre australi e antartiche francesi'),
(266, 'GA', 'GAB', 'Gabon', 'Gabun', 'Gabon', 'Gabon'),
(270, 'GM', 'GMB', 'Gambia', 'Gambia', 'Gambie', 'Gambia'),
(268, 'GE', 'GEO', 'Georgia', 'Georgien', 'Géorgie (pays)', 'Georgia'),
(288, 'GH', 'GHA', 'Ghana', 'Ghana', 'Ghana', 'Ghana'),
(292, 'GI', 'GIB', 'Gibraltar', 'Gibraltar', 'Gibraltar', 'Gibilterra'),
(308, 'GD', 'GRD', 'Grenada', 'Grenada', 'Grenade (pays)', 'Grenada'),
(300, 'GR', 'GRC', 'Greece', 'Griechenland', 'Grèce', 'Grecia'),
(304, 'GL', 'GRL', 'Greenland', 'Grönland', 'Groenland', 'Groenlandia'),
(312, 'GP', 'GLP', 'Guadeloupe', 'Guadeloupe', 'Guadeloupe', 'Guadalupa'),
(316, 'GU', 'GUM', 'Guam', 'Guam', 'Guam', 'Guam'),
(320, 'GT', 'GTM', 'Guatemala', 'Guatemala', 'Guatemala', 'Guatemala'),
(831, 'GG', 'GGY', 'Guernsey', 'Guernsey (Kanalinsel)', 'Guernesey', 'Guernsey'),
(324, 'GN', 'GIN', 'Guinea', 'Guinea', 'Guinée', 'Guinea'),
(624, 'GW', 'GNB', 'Guinea-Bissau', 'Guinea-Bissau', 'Guinée-Bissau', 'Guinea-Bissau'),
(328, 'GY', 'GUY', 'Guyana', 'Guyana', 'Guyana', 'Guyana'),
(332, 'HT', 'HTI', 'Haiti', 'Haiti', 'Haïti', 'Haiti'),
(334, 'HM', 'HMD', 'Heard Island and McDonald Islands', 'Heard und McDonaldinseln', 'Îles Heard-et-MacDonald', 'Isole Heard e McDonald'),
(340, 'HN', 'HND', 'Honduras', 'Honduras', 'Honduras', 'Honduras'),
(344, 'HK', 'HKG', 'Hong Kong', 'Hongkong', 'Hong Kong', 'Hong Kong'),
(356, 'IN', 'IND', 'India', 'Indien', 'Inde', 'India'),
(360, 'ID', 'IDN', 'Indonesia', 'Indonesien', 'Indonésie', 'Indonesia'),
(833, 'IM', 'IMN', 'Isle of Man', 'Insel Man', 'Île de Man', 'Isola di Man'),
(368, 'IQ', 'IRQ', 'Iraq', 'Irak', 'Irak', 'Iraq'),
(364, 'IR', 'IRN', 'Iran', 'Iran', 'Iran', 'Iran'),
(372, 'IE', 'IRL', 'Ireland', 'Irland', 'Irlande', 'Irlanda'),
(352, 'IS', 'ISL', 'Iceland', 'Island', 'Islande', 'Islanda'),
(376, 'IL', 'ISR', 'Israel', 'Israel', 'Israël', 'Israele'),
(380, 'IT', 'ITA', 'Italy', 'Italien', 'Italie', 'Italia'),
(388, 'JM', 'JAM', 'Jamaica', 'Jamaika', 'Jamaïque', 'Giamaica'),
(392, 'JP', 'JPN', 'Japan', 'Japan', 'Japon', 'Giappone'),
(887, 'YE', 'YEM', 'Yemen', 'Jemen', 'Yémen', 'Yemen'),
(832, 'JE', 'JEY', 'Jersey', 'Jersey (Kanalinsel)', 'Jersey', 'Jersey'),
(400, 'JO', 'JOR', 'Jordan', 'Jordanien', 'Jordanie', 'Giordania'),
(136, 'KY', 'CYM', 'Cayman Islands', 'Kaimaninseln', 'Îles Caïmans', 'Isole Cayman'),
(116, 'KH', 'KHM', 'Cambodia', 'Kambodscha', 'Cambodge', 'Cambogia'),
(120, 'CM', 'CMR', 'Cameroon', 'Kamerun', 'Cameroun', 'Camerun'),
(124, 'CA', 'CAN', 'Canada', 'Kanada', 'Canada', 'Canada'),
(132, 'CV', 'CPV', 'Cabo Verde', 'Kap Verde', 'Cap-Vert', 'Capo Verde'),
(398, 'KZ', 'KAZ', 'Kazakhstan', 'Kasachstan', 'Kazakhstan', 'Kazakistan'),
(634, 'QA', 'QAT', 'Qatar', 'Katar', 'Qatar', 'Qatar'),
(404, 'KE', 'KEN', 'Kenya', 'Kenia', 'Kenya', 'Kenya'),
(417, 'KG', 'KGZ', 'Kyrgyzstan', 'Kirgisistan', 'Kirghizistan', 'Kirghizistan'),
(296, 'KI', 'KIR', 'Kiribati', 'Kiribati', 'Kiribati', 'Kiribati'),
(166, 'CC', 'CCK', 'Cocos (Keeling) Islands', 'Kokosinseln', 'Îles Cocos', 'Isole Cocos (Keeling)'),
(170, 'CO', 'COL', 'Colombia', 'Kolumbien', 'Colombie', 'Colombia'),
(174, 'KM', 'COM', 'Comoros', 'Komoren', 'Comores (pays)', 'Comore'),
(178, 'CG', 'COG', 'Congo', 'Kongo', 'République démocratique du Congo', 'Rep. del Congo'),
(408, 'KP', 'PRK', 'Korea (Democratic People\'s Republic of)', 'Korea, Demokratische Volksrepublik (Nordkorea)', 'Corée du Nord', 'Corea del Nord'),
(410, 'KR', 'KOR', 'Korea (Republic of)', 'Korea, Republik (Südkorea)', 'Corée du Sud', 'Corea del Sud'),
(191, 'HR', 'HRV', 'Croatia', 'Kroatien', 'Croatie', 'Croazia'),
(192, 'CU', 'CUB', 'Cuba', 'Kuba', 'Cuba', 'Cuba'),
(414, 'KW', 'KWT', 'Kuwait', 'Kuwait', 'Koweït', 'Kuwait'),
(418, 'LA', 'LAO', 'Lao People\'s Democratic Republic', 'Laos, Demokratische Volksrepublik', 'Laos', 'Laos'),
(426, 'LS', 'LSO', 'Lesotho', 'Lesotho', 'Lesotho', 'Lesotho'),
(428, 'LV', 'LVA', 'Latvia', 'Lettland', 'Lettonie', 'Lettonia'),
(422, 'LB', 'LBN', 'Lebanon', 'Libanon', 'Liban', 'Libano'),
(430, 'LR', 'LBR', 'Liberia', 'Liberia', 'Liberia', 'Liberia'),
(434, 'LY', 'LBY', 'Libya', 'Libyen', 'Libye', 'Libia'),
(438, 'LI', 'LIE', 'Liechtenstein', 'Liechtenstein', 'Liechtenstein', 'Liechtenstein'),
(440, 'LT', 'LTU', 'Lithuania', 'Litauen', 'Lituanie', 'Lituania'),
(442, 'LU', 'LUX', 'Luxembourg', 'Luxemburg', 'Luxembourg (pays)', 'Lussemburgo'),
(446, 'MO', 'MAC', 'Macao', 'Macau', 'Macao', 'Macao'),
(450, 'MG', 'MDG', 'Madagascar', 'Madagaskar', 'Madagascar', 'Madagascar'),
(454, 'MW', 'MWI', 'Malawi', 'Malawi', 'Malawi', 'Malawi'),
(458, 'MY', 'MYS', 'Malaysia', 'Malaysia', 'Malaisie', 'Malesia'),
(462, 'MV', 'MDV', 'Maldives', 'Malediven', 'Maldives', 'Maldive'),
(466, 'ML', 'MLI', 'Mali', 'Mali', 'Mali', 'Mali'),
(470, 'MT', 'MLT', 'Malta', 'Malta', 'Malte', 'Malta'),
(504, 'MA', 'MAR', 'Morocco', 'Marokko', 'Maroc', 'Marocco'),
(584, 'MH', 'MHL', 'Marshall Islands', 'Marshallinseln', 'Îles Marshall (pays)', 'Isole Marshall'),
(474, 'MQ', 'MTQ', 'Martinique', 'Martinique', 'Martinique', 'Martinica'),
(478, 'MR', 'MRT', 'Mauritania', 'Mauretanien', 'Mauritanie', 'Mauritania'),
(480, 'MU', 'MUS', 'Mauritius', 'Mauritius', 'Maurice,Île', 'Mauritius'),
(175, 'YT', 'MYT', 'Mayotte', 'Mayotte', 'Mayotte', 'Mayotte'),
(807, 'MK', 'MKD', 'Macedonia', 'Mazedonien', 'République de Macédoine (pays)', 'Macedonia'),
(484, 'MX', 'MEX', 'Mexico', 'Mexiko', 'Mexique', 'Messico'),
(583, 'FM', 'FSM', 'Micronesia (Federated States of)', 'Mikronesien', 'Micronésie (pays)', 'Micronesia'),
(498, 'MD', 'MDA', 'Moldova (Republic of)', 'Moldawien (Republik Moldau)', 'Moldavie', 'Moldavia'),
(492, 'MC', 'MCO', 'Monaco', 'Monaco', 'Monaco', 'Monaco'),
(496, 'MN', 'MNG', 'Mongolia', 'Mongolei', 'Mongolie', 'Mongolia'),
(499, 'ME', 'MNE', 'Montenegro', 'Montenegro', 'Monténégro', 'Montenegro'),
(500, 'MS', 'MSR', 'Montserrat', 'Montserrat', 'Montserrat', 'Montserrat'),
(508, 'MZ', 'MOZ', 'Mozambique', 'Mosambik', 'Mozambique', 'Mozambico'),
(104, 'MM', 'MMR', 'Myanmar', 'Myanmar (Burma)', 'Birmanie', 'Birmania'),
(516, 'NA', 'NAM', 'Namibia', 'Namibia', 'Namibie', 'Namibia'),
(520, 'NR', 'NRU', 'Nauru', 'Nauru', 'Nauru', 'Nauru'),
(524, 'NP', 'NPL', 'Nepal', 'Nepal', 'Népal', 'Nepal'),
(540, 'NC', 'NCL', 'New Caledonia', 'Neukaledonien', 'Nouvelle-Calédonie', 'Nuova Caledonia'),
(554, 'NZ', 'NZL', 'New Zealand', 'Neuseeland', 'Nouvelle-Zélande', 'Nuova Zelanda'),
(558, 'NI', 'NIC', 'Nicaragua', 'Nicaragua', 'Nicaragua', 'Nicaragua'),
(528, 'NL', 'NLD', 'Netherlands', 'Niederlande', 'Pays-Bas', 'Paesi Bassi'),
(562, 'NE', 'NER', 'Niger', 'Niger', 'Niger', 'Niger'),
(566, 'NG', 'NGA', 'Nigeria', 'Nigeria', 'Nigeria', 'Nigeria'),
(570, 'NU', 'NIU', 'Niue', 'Niue', 'Niue', 'Niue'),
(580, 'MP', 'MNP', 'Northern Mariana Islands', 'Nördliche Marianen', 'Îles Mariannes du Nord', 'Isole Marianne Settentrionali'),
(574, 'NF', 'NFK', 'Norfolk Island', 'Norfolkinsel', 'Île Norfolk', 'Isola Norfolk'),
(578, 'NO', 'NOR', 'Norway', 'Norwegen', 'Norvège', 'Norvegia'),
(512, 'OM', 'OMN', 'Oman', 'Oman', 'Oman', 'Oman'),
(40, 'AT', 'AUT', 'Austria', 'Österreich', 'Autriche', 'Austria'),
(626, 'TL', 'TLS', 'Timor-Leste', 'Osttimor (Timor-Leste)', 'Timor oriental', 'Timor Est'),
(586, 'PK', 'PAK', 'Pakistan', 'Pakistan', 'Pakistan', 'Pakistan'),
(275, 'PS', 'PSE', 'Palestine, State of', 'Staat Palästina', 'Palestine', 'Palestina'),
(585, 'PW', 'PLW', 'Palau', 'Palau', 'Palaos', 'Palau'),
(591, 'PA', 'PAN', 'Panama', 'Panama', 'Panama', 'Panama'),
(598, 'PG', 'PNG', 'Papua New Guinea', 'Papua-Neuguinea', 'Papouasie-Nouvelle-Guinée', 'Papua Nuova Guinea'),
(600, 'PY', 'PRY', 'Paraguay', 'Paraguay', 'Paraguay', 'Paraguay'),
(604, 'PE', 'PER', 'Peru', 'Peru', 'Pérou', 'Perù'),
(608, 'PH', 'PHL', 'Philippines', 'Philippinen', 'Philippines', 'Filippine'),
(612, 'PN', 'PCN', 'Pitcairn', 'Pitcairninseln', 'Îles Pitcairn', 'Isole Pitcairn'),
(616, 'PL', 'POL', 'Poland', 'Polen', 'Pologne', 'Polonia'),
(620, 'PT', 'PRT', 'Portugal', 'Portugal', 'Portugal', 'Portogallo'),
(630, 'PR', 'PRI', 'Puerto Rico', 'Puerto Rico', 'Porto Rico', 'Porto Rico'),
(638, 'RE', 'REU', 'Réunion', 'Réunion', 'La Réunion', 'Riunione'),
(646, 'RW', 'RWA', 'Rwanda', 'Ruanda', 'Rwanda', 'Ruanda'),
(642, 'RO', 'ROU', 'Romania', 'Rumänien', 'Roumanie', 'Romania'),
(643, 'RU', 'RUS', 'Russian Federation', 'Russische Föderation', 'Russie', 'Russia'),
(90, 'SB', 'SLB', 'Solomon Islands', 'Salomonen', 'Salomon', 'Isole Salomone'),
(652, 'BL', 'BLM', 'Saint Barthélemy', 'Saint-Barthélemy', 'Saint-Barthélemy', 'Saint-Barthélemy'),
(663, 'MF', 'MAF', 'Saint Martin (French part)', 'Saint-Martin (franz. Teil)', 'Saint-Martin', 'Saint-Martin'),
(894, 'ZM', 'ZMB', 'Zambia', 'Sambia', 'Zambie', 'Zambia'),
(882, 'WS', 'WSM', 'Samoa', 'Samoa', 'Samoa', 'Samoa'),
(674, 'SM', 'SMR', 'San Marino', 'San Marino', 'Saint-Marin', 'San Marino'),
(678, 'ST', 'STP', 'Sao Tome and Principe', 'São Tomé und Príncipe', 'Sao Tomé-et-Principe', 'São Tomé e Príncipe'),
(682, 'SA', 'SAU', 'Saudi Arabia', 'Saudi-Arabien', 'Arabie saoudite', 'Arabia Saudita'),
(752, 'SE', 'SWE', 'Sweden', 'Schweden', 'Suède', 'Svezia'),
(756, 'CH', 'CHE', 'Switzerland', 'Schweiz', 'Suisse', 'Svizzera'),
(686, 'SN', 'SEN', 'Senegal', 'Senegal', 'Sénégal', 'Senegal'),
(688, 'RS', 'SRB', 'Serbia', 'Serbien', 'Serbie', 'Serbia'),
(690, 'SC', 'SYC', 'Seychelles', 'Seychellen', 'Seychelles', 'Seychelles'),
(694, 'SL', 'SLE', 'Sierra Leone', 'Sierra Leone', 'Sierra Leone', 'Sierra Leone'),
(716, 'ZW', 'ZWE', 'Zimbabwe', 'Simbabwe', 'Zimbabwe', 'Zimbabwe'),
(702, 'SG', 'SGP', 'Singapore', 'Singapur', 'Singapour', 'Singapore'),
(534, 'SX', 'SXM', 'Sint Maarten (Dutch part)', 'Sint Maarten (niederl. Teil)', 'Saint-Martin', 'Sint Maarten'),
(703, 'SK', 'SVK', 'Slovakia', 'Slowakei', 'Slovaquie', 'Slovacchia'),
(705, 'SI', 'SVN', 'Slovenia', 'Slowenien', 'Slovénie', 'Slovenia'),
(706, 'SO', 'SOM', 'Somalia', 'Somalia', 'Somalie', 'Somalia'),
(724, 'ES', 'ESP', 'Spain', 'Spanien', 'Espagne', 'Spagna'),
(144, 'LK', 'LKA', 'Sri Lanka', 'Sri Lanka', 'Sri Lanka', 'Sri Lanka'),
(654, 'SH', 'SHN', 'Saint Helena, Ascension and Tristan da Cunha', 'St. Helena', 'Sainte-Hélène, Ascension et Tristan da Cunha', 'Sant\'Elena, Ascensione e Tristan da Cunha'),
(659, 'KN', 'KNA', 'Saint Kitts and Nevis', 'St. Kitts und Nevis', 'Saint-Christophe-et-Niévès', 'Saint Kitts e Nevis'),
(662, 'LC', 'LCA', 'Saint Lucia', 'St. Lucia', 'Sainte-Lucie', 'Santa Lucia'),
(666, 'PM', 'SPM', 'Saint Pierre and Miquelon', 'Saint-Pierre und Miquelon', 'Saint-Pierre-et-Miquelon', 'Saint-Pierre e Miquelon'),
(670, 'VC', 'VCT', 'Saint Vincent and the Grenadines', 'St. Vincent und die Grenadinen', 'Saint-Vincent-et-les Grenadines', 'Saint Vincent e Grenadine'),
(710, 'ZA', 'ZAF', 'South Africa', 'Südafrika', 'Afrique du Sud', 'Sudafrica'),
(729, 'SD', 'SDN', 'Sudan', 'Sudan', 'Soudan', 'Sudan'),
(239, 'GS', 'SGS', 'South Georgia and the South Sandwich Islands', 'Südgeorgien und die Südlichen Sandwichinseln', 'Géorgie du Sud-et-les Îles Sandwich du Sud', 'Georgia del Sud e isole Sandwich meridionali'),
(728, 'SS', 'SSD', 'South Sudan', 'Südsudan', 'Soudan du Sud', 'Sudan del Sud'),
(740, 'SR', 'SUR', 'Suriname', 'Suriname', 'Suriname', 'Suriname'),
(744, 'SJ', 'SJM', 'Svalbard and Jan Mayen', 'Svalbard und Jan Mayen', 'Svalbard et ile Jan Mayen', 'Svalbard e Jan Mayen'),
(748, 'SZ', 'SWZ', 'Swaziland', 'Swasiland', 'Swaziland', 'Swaziland'),
(760, 'SY', 'SYR', 'Syrian Arab Republic', 'Syrien', 'Syrie', 'Siria'),
(762, 'TJ', 'TJK', 'Tajikistan', 'Tadschikistan', 'Tadjikistan', 'Tagikistan'),
(158, 'TW', 'TWN', 'Taiwan, Province of China', 'Republik China (Taiwan)', 'Taïwan / (République de Chine (Taïwan))', 'Taiwan'),
(834, 'TZ', 'TZA', 'Tanzania, United Republic of', 'Tansania, Vereinigte Republik', 'Tanzanie', 'Tanzania'),
(764, 'TH', 'THA', 'Thailand', 'Thailand', 'Thaïlande', 'Thailandia'),
(768, 'TG', 'TGO', 'Togo', 'Togo', 'Togo', 'Togo'),
(772, 'TK', 'TKL', 'Tokelau', 'Tokelau', 'Tokelau', 'Tokelau'),
(776, 'TO', 'TON', 'Tonga', 'Tonga', 'Tonga', 'Tonga'),
(780, 'TT', 'TTO', 'Trinidad and Tobago', 'Trinidad und Tobago', 'Trinité-et-Tobago', 'Trinidad e Tobago'),
(148, 'TD', 'TCD', 'Chad', 'Tschad', 'Tchad', 'Ciad'),
(203, 'CZ', 'CZE', 'Czechia', 'Tschechien', 'Tchéquie', 'Rep. Ceca'),
(788, 'TN', 'TUN', 'Tunisia', 'Tunesien', 'Tunisie', 'Tunisia'),
(792, 'TR', 'TUR', 'Turkey', 'Türkei', 'Turquie', 'Turchia'),
(795, 'TM', 'TKM', 'Turkmenistan', 'Turkmenistan', 'Turkménistan', 'Turkmenistan'),
(796, 'TC', 'TCA', 'Turks and Caicos Islands', 'Turks- und Caicosinseln', 'Îles Turks-et-Caïcos', 'Turks e Caicos'),
(798, 'TV', 'TUV', 'Tuvalu', 'Tuvalu', 'Tuvalu', 'Tuvalu'),
(800, 'UG', 'UGA', 'Uganda', 'Uganda', 'Ouganda', 'Uganda'),
(804, 'UA', 'UKR', 'Ukraine', 'Ukraine', 'Ukraine', 'Ucraina'),
(348, 'HU', 'HUN', 'Hungary', 'Ungarn', 'Hongrie', 'Ungheria'),
(581, 'UM', 'UMI', 'United States Minor Outlying Islands', 'United States Minor Outlying Islands', 'Îles mineures éloignées des États-Unis', 'Isole minori esterne degli Stati Uniti'),
(858, 'UY', 'URY', 'Uruguay', 'Uruguay', 'Uruguay', 'Uruguay'),
(860, 'UZ', 'UZB', 'Uzbekistan', 'Usbekistan', 'Ouzbékistan', 'Uzbekistan'),
(548, 'VU', 'VUT', 'Vanuatu', 'Vanuatu', 'Vanuatu', 'Vanuatu'),
(336, 'VA', 'VAT', 'Holy See', 'Vatikanstadt', 'Saint-Siège (État de la Cité du Vatican)', 'Città del Vaticano'),
(862, 'VE', 'VEN', 'Venezuela (Bolivarian Republic of)', 'Venezuela', 'Venezuela', 'Venezuela'),
(784, 'AE', 'ARE', 'United Arab Emirates', 'Vereinigte Arabische Emirate', 'Émirats arabes unis', 'Emirati Arabi Uniti'),
(840, 'US', 'USA', 'United States of America', 'Vereinigte Staaten von Amerika', 'États-Unis', 'Stati Uniti'),
(826, 'GB', 'GBR', 'United Kingdom of Great Britain and Northern Irela', 'Vereinigtes Königreich Großbritannien und Nordirland', 'Royaume-Uni', 'Regno Unito'),
(704, 'VN', 'VNM', 'Viet Nam', 'Vietnam', 'Viêt Nam', 'Vietnam'),
(876, 'WF', 'WLF', 'Wallis and Futuna', 'Wallis und Futuna', 'Wallis-et-Futuna', 'Wallis e Futuna'),
(162, 'CX', 'CXR', 'Christmas Island', 'Weihnachtsinsel', 'Île Christmas', 'Isola di Natale'),
(732, 'EH', 'ESH', 'Western Sahara', 'Westsahara', 'République arabe sahraouie démocratique', 'Sahara Occidentale'),
(140, 'CF', 'CAF', 'Central African Republic', 'Zentralafrikanische Republik', 'République centrafricaine', 'Rep. Centrafricana'),
(196, 'CY', 'CYP', 'Cyprus', 'Zypern', 'Chypre (pays)', 'Cipro'),
(895, 'XK', 'XKX', 'Kosovo', 'Kosovo', 'Kosovo', 'Kosovo'),
(896, 'AN', 'ANT', 'Netherlands Antilles', 'Niederländische Antillen', 'Antilles néerlandaises', 'Antille Olandesi');

