INSERT INTO `loc_countries` (`id`, `name`, `code`, `alpha_3`, `name_de`, `name_fr`, `name_it`) VALUES
(4, 'Afghanistan', 'AF', 'AFG', 'Afghanistan', 'Afghanistan', 'Afghanistan'),
(8, 'Albania', 'AL', 'ALB', 'Albanien', 'Albanie', 'Albania'),
(10, 'Antarctica', 'AQ', 'ATA', 'Antarktika (Sonderstatus durch Antarktis-Vertrag)', 'Antarctique', 'Antartide'),
(12, 'Algeria', 'DZ', 'DZA', 'Algerien', 'Algérie', 'Algeria'),
(16, 'American Samoa', 'AS', 'ASM', 'Amerikanisch-Samoa', 'Samoa américaines', 'Samoa Americane'),
(20, 'Andorra', 'AD', 'AND', 'Andorra', 'Andorre', 'Andorra'),
(24, 'Angola', 'AO', 'AGO', 'Angola', 'Angola', 'Angola'),
(28, 'Antigua and Barbuda', 'AG', 'ATG', 'Antigua und Barbuda', 'Antigua-et-Barbuda', 'Antigua e Barbuda'),
(31, 'Azerbaijan', 'AZ', 'AZE', 'Aserbaidschan', 'Azerbaïdjan', 'Azerbaigian'),
(32, 'Argentina', 'AR', 'ARG', 'Argentinien', 'Argentine', 'Argentina'),
(36, 'Australia', 'AU', 'AUS', 'Australien', 'Australie', 'Australia'),
(40, 'Austria', 'AT', 'AUT', 'Österreich', 'Autriche', 'Austria'),
(44, 'Bahamas', 'BS', 'BHS', 'Bahamas', 'Bahamas', 'Bahamas'),
(48, 'Bahrain', 'BH', 'BHR', 'Bahrain', 'Bahreïn', 'Bahrein'),
(50, 'Bangladesh', 'BD', 'BGD', 'Bangladesch', 'Bangladesh', 'Bangladesh'),
(51, 'Armenia', 'AM', 'ARM', 'Armenien', 'Arménie', 'Armenia'),
(52, 'Barbados', 'BB', 'BRB', 'Barbados', 'Barbade', 'Barbados'),
(56, 'Belgium', 'BE', 'BEL', 'Belgien', 'Belgique', 'Belgio'),
(60, 'Bermuda', 'BM', 'BMU', 'Bermuda', 'Bermudes', 'Bermuda'),
(64, 'Bhutan', 'BT', 'BTN', 'Bhutan', 'Bhoutan', 'Bhutan'),
(68, 'Bolivia (Plurinational State of)', 'BO', 'BOL', 'Bolivien', 'Bolivie', 'Bolivia'),
(70, 'Bosnia and Herzegovina', 'BA', 'BIH', 'Bosnien und Herzegowina', 'Bosnie-Herzégovine', 'Bosnia ed Erzegovina'),
(72, 'Botswana', 'BW', 'BWA', 'Botswana', 'Botswana', 'Botswana'),
(74, 'Bouvet Island', 'BV', 'BVT', 'Bouvetinsel', 'Île Bouvet', 'Isola Bouvet'),
(76, 'Brazil', 'BR', 'BRA', 'Brasilien', 'Brésil', 'Brasile'),
(84, 'Belize', 'BZ', 'BLZ', 'Belize', 'Belize', 'Belize'),
(86, 'British Indian Ocean Territory', 'IO', 'IOT', 'Britisches Territorium im Indischen Ozean', 'Territoire britannique de l\'océan Indien', 'Territorio britannico dell\'Oceano Indiano'),
(90, 'Solomon Islands', 'SB', 'SLB', 'Salomonen', 'Salomon', 'Isole Salomone'),
(92, 'Virgin Islands (British)', 'VG', 'VGB', 'Britische Jungferninseln', 'Îles Vierges britanniques', 'Isole Vergini britanniche'),
(96, 'Brunei Darussalam', 'BN', 'BRN', 'Brunei Darussalam', 'Brunei', 'Brunei'),
(100, 'Bulgaria', 'BG', 'BGR', 'Bulgarien', 'Bulgarie', 'Bulgaria'),
(104, 'Myanmar', 'MM', 'MMR', 'Myanmar (Burma)', 'Birmanie', 'Birmania'),
(108, 'Burundi', 'BI', 'BDI', 'Burundi', 'Burundi', 'Burundi'),
(112, 'Belarus', 'BY', 'BLR', 'Belarus (Weißrussland)', 'Biélorussie', 'Bielorussia'),
(116, 'Cambodia', 'KH', 'KHM', 'Kambodscha', 'Cambodge', 'Cambogia'),
(120, 'Cameroon', 'CM', 'CMR', 'Kamerun', 'Cameroun', 'Camerun'),
(124, 'Canada', 'CA', 'CAN', 'Kanada', 'Canada', 'Canada'),
(132, 'Cabo Verde', 'CV', 'CPV', 'Kap Verde', 'Cap-Vert', 'Capo Verde'),
(136, 'Cayman Islands', 'KY', 'CYM', 'Kaimaninseln', 'Îles Caïmans', 'Isole Cayman'),
(140, 'Central African Republic', 'CF', 'CAF', 'Zentralafrikanische Republik', 'République centrafricaine', 'Rep. Centrafricana'),
(144, 'Sri Lanka', 'LK', 'LKA', 'Sri Lanka', 'Sri Lanka', 'Sri Lanka'),
(148, 'Chad', 'TD', 'TCD', 'Tschad', 'Tchad', 'Ciad'),
(152, 'Chile', 'CL', 'CHL', 'Chile', 'Chili', 'Cile'),
(156, 'China', 'CN', 'CHN', 'China', 'Chine', 'Cina'),
(158, 'Taiwan, Province of China', 'TW', 'TWN', 'Republik China (Taiwan)', 'Taïwan / (République de Chine (Taïwan))', 'Taiwan'),
(162, 'Christmas Island', 'CX', 'CXR', 'Weihnachtsinsel', 'Île Christmas', 'Isola di Natale'),
(166, 'Cocos (Keeling) Islands', 'CC', 'CCK', 'Kokosinseln', 'Îles Cocos', 'Isole Cocos (Keeling)'),
(170, 'Colombia', 'CO', 'COL', 'Kolumbien', 'Colombie', 'Colombia'),
(174, 'Comoros', 'KM', 'COM', 'Komoren', 'Comores (pays)', 'Comore'),
(175, 'Mayotte', 'YT', 'MYT', 'Mayotte', 'Mayotte', 'Mayotte'),
(178, 'Congo', 'CG', 'COG', 'Kongo', 'République démocratique du Congo', 'Rep. del Congo'),
(184, 'Cook Islands', 'CK', 'COK', 'Cookinseln', 'Îles Cook', 'Isole Cook'),
(188, 'Costa Rica', 'CR', 'CRI', 'Costa Rica', 'Costa Rica', 'Costa Rica'),
(191, 'Croatia', 'HR', 'HRV', 'Kroatien', 'Croatie', 'Croazia'),
(192, 'Cuba', 'CU', 'CUB', 'Kuba', 'Cuba', 'Cuba'),
(196, 'Cyprus', 'CY', 'CYP', 'Zypern', 'Chypre (pays)', 'Cipro'),
(203, 'Czechia', 'CZ', 'CZE', 'Tschechien', 'Tchéquie', 'Rep. Ceca'),
(204, 'Benin', 'BJ', 'BEN', 'Benin', 'Bénin', 'Benin'),
(208, 'Denmark', 'DK', 'DNK', 'Dänemark', 'Danemark', 'Danimarca'),
(212, 'Dominica', 'DM', 'DMA', 'Dominica', 'Dominique', 'Dominica'),
(214, 'Dominican Republic', 'DO', 'DOM', 'Dominikanische Republik', 'République dominicaine', 'Rep. Dominicana'),
(218, 'Ecuador', 'EC', 'ECU', 'Ecuador', 'Équateur (pays)', 'Ecuador'),
(222, 'El Salvador', 'SV', 'SLV', 'El Salvador', 'Salvador', 'El Salvador'),
(226, 'Equatorial Guinea', 'GQ', 'GNQ', 'Äquatorialguinea', 'Guinée équatoriale', 'Guinea Equatoriale'),
(231, 'Ethiopia', 'ET', 'ETH', 'Äthiopien', 'Éthiopie', 'Etiopia'),
(232, 'Eritrea', 'ER', 'ERI', 'Eritrea', 'Érythrée', 'Eritrea'),
(233, 'Estonia', 'EE', 'EST', 'Estland', 'Estonie', 'Estonia'),
(234, 'Faroe Islands', 'FO', 'FRO', 'Färöer', 'Îles Féroé', 'Fær Øer'),
(238, 'Falkland Islands (Malvinas)', 'FK', 'FLK', 'Falklandinseln', 'Malouines', 'Isole Falkland'),
(239, 'South Georgia and the South Sandwich Islands', 'GS', 'SGS', 'Südgeorgien und die Südlichen Sandwichinseln', 'Géorgie du Sud-et-les Îles Sandwich du Sud', 'Georgia del Sud e isole Sandwich meridionali'),
(242, 'Fiji', 'FJ', 'FJI', 'Fidschi', 'Fidji', 'Figi'),
(246, 'Finland', 'FI', 'FIN', 'Finnland', 'Finlande', 'Finlandia'),
(248, 'Åland Islands', 'AX', 'ALA', 'Åland', 'Îles Åland', 'Isole Åland'),
(250, 'France', 'FR', 'FRA', 'Frankreich', 'France', 'Francia'),
(254, 'French Guiana', 'GF', 'GUF', 'Französisch-Guayana', 'Guyane', 'Guyana francese'),
(258, 'French Polynesia', 'PF', 'PYF', 'Französisch-Polynesien', 'Polynésie française', 'Polinesia Francese'),
(260, 'French Southern Territories', 'TF', 'ATF', 'Französische Süd- und Antarktisgebiete', 'Terres australes et antarctiques françaises', 'Terre australi e antartiche francesi'),
(262, 'Djibouti', 'DJ', 'DJI', 'Dschibuti', 'Djibouti', 'Gibuti'),
(266, 'Gabon', 'GA', 'GAB', 'Gabun', 'Gabon', 'Gabon'),
(268, 'Georgia', 'GE', 'GEO', 'Georgien', 'Géorgie (pays)', 'Georgia'),
(270, 'Gambia', 'GM', 'GMB', 'Gambia', 'Gambie', 'Gambia'),
(275, 'Palestine, State of', 'PS', 'PSE', 'Staat Palästina', 'Palestine', 'Palestina'),
(276, 'Germany', 'DE', 'DEU', 'Deutschland', 'Allemagne', 'Germania'),
(288, 'Ghana', 'GH', 'GHA', 'Ghana', 'Ghana', 'Ghana'),
(292, 'Gibraltar', 'GI', 'GIB', 'Gibraltar', 'Gibraltar', 'Gibilterra'),
(296, 'Kiribati', 'KI', 'KIR', 'Kiribati', 'Kiribati', 'Kiribati'),
(300, 'Greece', 'GR', 'GRC', 'Griechenland', 'Grèce', 'Grecia'),
(304, 'Greenland', 'GL', 'GRL', 'Grönland', 'Groenland', 'Groenlandia'),
(308, 'Grenada', 'GD', 'GRD', 'Grenada', 'Grenade (pays)', 'Grenada'),
(312, 'Guadeloupe', 'GP', 'GLP', 'Guadeloupe', 'Guadeloupe', 'Guadalupa'),
(316, 'Guam', 'GU', 'GUM', 'Guam', 'Guam', 'Guam'),
(320, 'Guatemala', 'GT', 'GTM', 'Guatemala', 'Guatemala', 'Guatemala'),
(324, 'Guinea', 'GN', 'GIN', 'Guinea', 'Guinée', 'Guinea'),
(328, 'Guyana', 'GY', 'GUY', 'Guyana', 'Guyana', 'Guyana'),
(332, 'Haiti', 'HT', 'HTI', 'Haiti', 'Haïti', 'Haiti'),
(334, 'Heard Island and McDonald Islands', 'HM', 'HMD', 'Heard und McDonaldinseln', 'Îles Heard-et-MacDonald', 'Isole Heard e McDonald'),
(336, 'Holy See', 'VA', 'VAT', 'Vatikanstadt', 'Saint-Siège (État de la Cité du Vatican)', 'Città del Vaticano'),
(340, 'Honduras', 'HN', 'HND', 'Honduras', 'Honduras', 'Honduras'),
(344, 'Hong Kong', 'HK', 'HKG', 'Hongkong', 'Hong Kong', 'Hong Kong'),
(348, 'Hungary', 'HU', 'HUN', 'Ungarn', 'Hongrie', 'Ungheria'),
(352, 'Iceland', 'IS', 'ISL', 'Island', 'Islande', 'Islanda'),
(356, 'India', 'IN', 'IND', 'Indien', 'Inde', 'India'),
(360, 'Indonesia', 'ID', 'IDN', 'Indonesien', 'Indonésie', 'Indonesia'),
(364, 'Iran', 'IR', 'IRN', 'Iran', 'Iran', 'Iran'),
(368, 'Iraq', 'IQ', 'IRQ', 'Irak', 'Irak', 'Iraq'),
(372, 'Ireland', 'IE', 'IRL', 'Irland', 'Irlande', 'Irlanda'),
(376, 'Israel', 'IL', 'ISR', 'Israel', 'Israël', 'Israele'),
(380, 'Italy', 'IT', 'ITA', 'Italien', 'Italie', 'Italia'),
(384, 'Ivory Coast\n', 'CI', 'CIV', 'Côte d’Ivoire (Elfenbeinküste)', 'Côte d\'Ivoire', 'Costa d\'Avorio'),
(388, 'Jamaica', 'JM', 'JAM', 'Jamaika', 'Jamaïque', 'Giamaica'),
(392, 'Japan', 'JP', 'JPN', 'Japan', 'Japon', 'Giappone'),
(398, 'Kazakhstan', 'KZ', 'KAZ', 'Kasachstan', 'Kazakhstan', 'Kazakistan'),
(400, 'Jordan', 'JO', 'JOR', 'Jordanien', 'Jordanie', 'Giordania'),
(404, 'Kenya', 'KE', 'KEN', 'Kenia', 'Kenya', 'Kenya'),
(408, 'Korea (Democratic People\'s Republic of)', 'KP', 'PRK', 'Korea, Demokratische Volksrepublik (Nordkorea)', 'Corée du Nord', 'Corea del Nord'),
(410, 'Korea (Republic of)', 'KR', 'KOR', 'Korea, Republik (Südkorea)', 'Corée du Sud', 'Corea del Sud'),
(414, 'Kuwait', 'KW', 'KWT', 'Kuwait', 'Koweït', 'Kuwait'),
(417, 'Kyrgyzstan', 'KG', 'KGZ', 'Kirgisistan', 'Kirghizistan', 'Kirghizistan'),
(418, 'Lao People\'s Democratic Republic', 'LA', 'LAO', 'Laos, Demokratische Volksrepublik', 'Laos', 'Laos'),
(422, 'Lebanon', 'LB', 'LBN', 'Libanon', 'Liban', 'Libano'),
(426, 'Lesotho', 'LS', 'LSO', 'Lesotho', 'Lesotho', 'Lesotho'),
(428, 'Latvia', 'LV', 'LVA', 'Lettland', 'Lettonie', 'Lettonia'),
(430, 'Liberia', 'LR', 'LBR', 'Liberia', 'Liberia', 'Liberia'),
(434, 'Libya', 'LY', 'LBY', 'Libyen', 'Libye', 'Libia'),
(438, 'Liechtenstein', 'LI', 'LIE', 'Liechtenstein', 'Liechtenstein', 'Liechtenstein'),
(440, 'Lithuania', 'LT', 'LTU', 'Litauen', 'Lituanie', 'Lituania'),
(442, 'Luxembourg', 'LU', 'LUX', 'Luxemburg', 'Luxembourg (pays)', 'Lussemburgo'),
(446, 'Macao', 'MO', 'MAC', 'Macau', 'Macao', 'Macao'),
(450, 'Madagascar', 'MG', 'MDG', 'Madagaskar', 'Madagascar', 'Madagascar'),
(454, 'Malawi', 'MW', 'MWI', 'Malawi', 'Malawi', 'Malawi'),
(458, 'Malaysia', 'MY', 'MYS', 'Malaysia', 'Malaisie', 'Malesia'),
(462, 'Maldives', 'MV', 'MDV', 'Malediven', 'Maldives', 'Maldive'),
(466, 'Mali', 'ML', 'MLI', 'Mali', 'Mali', 'Mali'),
(470, 'Malta', 'MT', 'MLT', 'Malta', 'Malte', 'Malta'),
(474, 'Martinique', 'MQ', 'MTQ', 'Martinique', 'Martinique', 'Martinica'),
(478, 'Mauritania', 'MR', 'MRT', 'Mauretanien', 'Mauritanie', 'Mauritania'),
(480, 'Mauritius', 'MU', 'MUS', 'Mauritius', 'Maurice,Île', 'Mauritius'),
(484, 'Mexico', 'MX', 'MEX', 'Mexiko', 'Mexique', 'Messico'),
(492, 'Monaco', 'MC', 'MCO', 'Monaco', 'Monaco', 'Monaco'),
(496, 'Mongolia', 'MN', 'MNG', 'Mongolei', 'Mongolie', 'Mongolia'),
(498, 'Moldova (Republic of)', 'MD', 'MDA', 'Moldawien (Republik Moldau)', 'Moldavie', 'Moldavia'),
(499, 'Montenegro', 'ME', 'MNE', 'Montenegro', 'Monténégro', 'Montenegro'),
(500, 'Montserrat', 'MS', 'MSR', 'Montserrat', 'Montserrat', 'Montserrat'),
(504, 'Morocco', 'MA', 'MAR', 'Marokko', 'Maroc', 'Marocco'),
(508, 'Mozambique', 'MZ', 'MOZ', 'Mosambik', 'Mozambique', 'Mozambico'),
(512, 'Oman', 'OM', 'OMN', 'Oman', 'Oman', 'Oman'),
(516, 'Namibia', 'NA', 'NAM', 'Namibia', 'Namibie', 'Namibia'),
(520, 'Nauru', 'NR', 'NRU', 'Nauru', 'Nauru', 'Nauru'),
(524, 'Nepal', 'NP', 'NPL', 'Nepal', 'Népal', 'Nepal'),
(528, 'Netherlands', 'NL', 'NLD', 'Niederlande', 'Pays-Bas', 'Paesi Bassi'),
(531, 'Curaçao', 'CW', 'CUW', 'Curaçao', 'Curaçao', 'Curaçao'),
(533, 'Aruba', 'AW', 'ABW', 'Aruba', 'Aruba', 'Aruba'),
(534, 'Sint Maarten (Dutch part)', 'SX', 'SXM', 'Sint Maarten (niederl. Teil)', 'Saint-Martin', 'Sint Maarten'),
(535, 'Bonaire, Sint Eustatius and Saba', 'BQ', 'BES', 'Bonaire, Sint Eustatius und Saba (Niederlande)', 'Pays-Bas caribéens', 'Isole BES'),
(540, 'New Caledonia', 'NC', 'NCL', 'Neukaledonien', 'Nouvelle-Calédonie', 'Nuova Caledonia'),
(548, 'Vanuatu', 'VU', 'VUT', 'Vanuatu', 'Vanuatu', 'Vanuatu'),
(554, 'New Zealand', 'NZ', 'NZL', 'Neuseeland', 'Nouvelle-Zélande', 'Nuova Zelanda'),
(558, 'Nicaragua', 'NI', 'NIC', 'Nicaragua', 'Nicaragua', 'Nicaragua'),
(562, 'Niger', 'NE', 'NER', 'Niger', 'Niger', 'Niger'),
(566, 'Nigeria', 'NG', 'NGA', 'Nigeria', 'Nigeria', 'Nigeria'),
(570, 'Niue', 'NU', 'NIU', 'Niue', 'Niue', 'Niue'),
(574, 'Norfolk Island', 'NF', 'NFK', 'Norfolkinsel', 'Île Norfolk', 'Isola Norfolk'),
(578, 'Norway', 'NO', 'NOR', 'Norwegen', 'Norvège', 'Norvegia'),
(580, 'Northern Mariana Islands', 'MP', 'MNP', 'Nördliche Marianen', 'Îles Mariannes du Nord', 'Isole Marianne Settentrionali'),
(581, 'United States Minor Outlying Islands', 'UM', 'UMI', 'United States Minor Outlying Islands', 'Îles mineures éloignées des États-Unis', 'Isole minori esterne degli Stati Uniti'),
(583, 'Micronesia (Federated States of)', 'FM', 'FSM', 'Mikronesien', 'Micronésie (pays)', 'Micronesia'),
(584, 'Marshall Islands', 'MH', 'MHL', 'Marshallinseln', 'Îles Marshall (pays)', 'Isole Marshall'),
(585, 'Palau', 'PW', 'PLW', 'Palau', 'Palaos', 'Palau'),
(586, 'Pakistan', 'PK', 'PAK', 'Pakistan', 'Pakistan', 'Pakistan'),
(591, 'Panama', 'PA', 'PAN', 'Panama', 'Panama', 'Panama'),
(598, 'Papua New Guinea', 'PG', 'PNG', 'Papua-Neuguinea', 'Papouasie-Nouvelle-Guinée', 'Papua Nuova Guinea'),
(600, 'Paraguay', 'PY', 'PRY', 'Paraguay', 'Paraguay', 'Paraguay'),
(604, 'Peru', 'PE', 'PER', 'Peru', 'Pérou', 'Perù'),
(608, 'Philippines', 'PH', 'PHL', 'Philippinen', 'Philippines', 'Filippine'),
(612, 'Pitcairn', 'PN', 'PCN', 'Pitcairninseln', 'Îles Pitcairn', 'Isole Pitcairn'),
(616, 'Poland', 'PL', 'POL', 'Polen', 'Pologne', 'Polonia'),
(620, 'Portugal', 'PT', 'PRT', 'Portugal', 'Portugal', 'Portogallo'),
(624, 'Guinea-Bissau', 'GW', 'GNB', 'Guinea-Bissau', 'Guinée-Bissau', 'Guinea-Bissau'),
(626, 'Timor-Leste', 'TL', 'TLS', 'Osttimor (Timor-Leste)', 'Timor oriental', 'Timor Est'),
(630, 'Puerto Rico', 'PR', 'PRI', 'Puerto Rico', 'Porto Rico', 'Porto Rico'),
(634, 'Qatar', 'QA', 'QAT', 'Katar', 'Qatar', 'Qatar'),
(638, 'Réunion', 'RE', 'REU', 'Réunion', 'La Réunion', 'Riunione'),
(642, 'Romania', 'RO', 'ROU', 'Rumänien', 'Roumanie', 'Romania'),
(643, 'Russian Federation', 'RU', 'RUS', 'Russische Föderation', 'Russie', 'Russia'),
(646, 'Rwanda', 'RW', 'RWA', 'Ruanda', 'Rwanda', 'Ruanda'),
(652, 'Saint Barthélemy', 'BL', 'BLM', 'Saint-Barthélemy', 'Saint-Barthélemy', 'Saint-Barthélemy'),
(654, 'Saint Helena, Ascension and Tristan da Cunha', 'SH', 'SHN', 'St. Helena', 'Sainte-Hélène, Ascension et Tristan da Cunha', 'Sant\'Elena, Ascensione e Tristan da Cunha'),
(659, 'Saint Kitts and Nevis', 'KN', 'KNA', 'St. Kitts und Nevis', 'Saint-Christophe-et-Niévès', 'Saint Kitts e Nevis'),
(660, 'Anguilla', 'AI', 'AIA', 'Anguilla', 'Anguilla', 'Anguilla'),
(662, 'Saint Lucia', 'LC', 'LCA', 'St. Lucia', 'Sainte-Lucie', 'Santa Lucia'),
(663, 'Saint Martin (French part)', 'MF', 'MAF', 'Saint-Martin (franz. Teil)', 'Saint-Martin', 'Saint-Martin'),
(666, 'Saint Pierre and Miquelon', 'PM', 'SPM', 'Saint-Pierre und Miquelon', 'Saint-Pierre-et-Miquelon', 'Saint-Pierre e Miquelon'),
(670, 'Saint Vincent and the Grenadines', 'VC', 'VCT', 'St. Vincent und die Grenadinen', 'Saint-Vincent-et-les Grenadines', 'Saint Vincent e Grenadine'),
(674, 'San Marino', 'SM', 'SMR', 'San Marino', 'Saint-Marin', 'San Marino'),
(678, 'Sao Tome and Principe', 'ST', 'STP', 'São Tomé und Príncipe', 'Sao Tomé-et-Principe', 'São Tomé e Príncipe'),
(682, 'Saudi Arabia', 'SA', 'SAU', 'Saudi-Arabien', 'Arabie saoudite', 'Arabia Saudita'),
(686, 'Senegal', 'SN', 'SEN', 'Senegal', 'Sénégal', 'Senegal'),
(688, 'Serbia', 'RS', 'SRB', 'Serbien', 'Serbie', 'Serbia'),
(690, 'Seychelles', 'SC', 'SYC', 'Seychellen', 'Seychelles', 'Seychelles'),
(694, 'Sierra Leone', 'SL', 'SLE', 'Sierra Leone', 'Sierra Leone', 'Sierra Leone'),
(702, 'Singapore', 'SG', 'SGP', 'Singapur', 'Singapour', 'Singapore'),
(703, 'Slovakia', 'SK', 'SVK', 'Slowakei', 'Slovaquie', 'Slovacchia'),
(704, 'Viet Nam', 'VN', 'VNM', 'Vietnam', 'Viêt Nam', 'Vietnam'),
(705, 'Slovenia', 'SI', 'SVN', 'Slowenien', 'Slovénie', 'Slovenia'),
(706, 'Somalia', 'SO', 'SOM', 'Somalia', 'Somalie', 'Somalia'),
(710, 'South Africa', 'ZA', 'ZAF', 'Südafrika', 'Afrique du Sud', 'Sudafrica'),
(716, 'Zimbabwe', 'ZW', 'ZWE', 'Simbabwe', 'Zimbabwe', 'Zimbabwe'),
(724, 'Spain', 'ES', 'ESP', 'Spanien', 'Espagne', 'Spagna'),
(728, 'South Sudan', 'SS', 'SSD', 'Südsudan', 'Soudan du Sud', 'Sudan del Sud'),
(729, 'Sudan', 'SD', 'SDN', 'Sudan', 'Soudan', 'Sudan'),
(732, 'Western Sahara', 'EH', 'ESH', 'Westsahara', 'République arabe sahraouie démocratique', 'Sahara Occidentale'),
(740, 'Suriname', 'SR', 'SUR', 'Suriname', 'Suriname', 'Suriname'),
(744, 'Svalbard and Jan Mayen', 'SJ', 'SJM', 'Svalbard und Jan Mayen', 'Svalbard et ile Jan Mayen', 'Svalbard e Jan Mayen'),
(748, 'Swaziland', 'SZ', 'SWZ', 'Swasiland', 'Swaziland', 'Swaziland'),
(752, 'Sweden', 'SE', 'SWE', 'Schweden', 'Suède', 'Svezia'),
(756, 'Switzerland', 'CH', 'CHE', 'Schweiz', 'Suisse', 'Svizzera'),
(760, 'Syrian Arab Republic', 'SY', 'SYR', 'Syrien', 'Syrie', 'Siria'),
(762, 'Tajikistan', 'TJ', 'TJK', 'Tadschikistan', 'Tadjikistan', 'Tagikistan'),
(764, 'Thailand', 'TH', 'THA', 'Thailand', 'Thaïlande', 'Thailandia'),
(768, 'Togo', 'TG', 'TGO', 'Togo', 'Togo', 'Togo'),
(772, 'Tokelau', 'TK', 'TKL', 'Tokelau', 'Tokelau', 'Tokelau'),
(776, 'Tonga', 'TO', 'TON', 'Tonga', 'Tonga', 'Tonga'),
(780, 'Trinidad and Tobago', 'TT', 'TTO', 'Trinidad und Tobago', 'Trinité-et-Tobago', 'Trinidad e Tobago'),
(784, 'United Arab Emirates', 'AE', 'ARE', 'Vereinigte Arabische Emirate', 'Émirats arabes unis', 'Emirati Arabi Uniti'),
(788, 'Tunisia', 'TN', 'TUN', 'Tunesien', 'Tunisie', 'Tunisia'),
(792, 'Turkey', 'TR', 'TUR', 'Türkei', 'Turquie', 'Turchia'),
(795, 'Turkmenistan', 'TM', 'TKM', 'Turkmenistan', 'Turkménistan', 'Turkmenistan'),
(796, 'Turks and Caicos Islands', 'TC', 'TCA', 'Turks- und Caicosinseln', 'Îles Turks-et-Caïcos', 'Turks e Caicos'),
(798, 'Tuvalu', 'TV', 'TUV', 'Tuvalu', 'Tuvalu', 'Tuvalu'),
(800, 'Uganda', 'UG', 'UGA', 'Uganda', 'Ouganda', 'Uganda'),
(804, 'Ukraine', 'UA', 'UKR', 'Ukraine', 'Ukraine', 'Ucraina'),
(807, 'Macedonia', 'MK', 'MKD', 'Mazedonien', 'République de Macédoine (pays)', 'Macedonia'),
(818, 'Egypt', 'EG', 'EGY', 'Ägypten', 'Égypte', 'Egitto'),
(826, 'United Kingdom of Great Britain and Northern Irela', 'GB', 'GBR', 'Vereinigtes Königreich Großbritannien und Nordirland', 'Royaume-Uni', 'Regno Unito'),
(831, 'Guernsey', 'GG', 'GGY', 'Guernsey (Kanalinsel)', 'Guernesey', 'Guernsey'),
(832, 'Jersey', 'JE', 'JEY', 'Jersey (Kanalinsel)', 'Jersey', 'Jersey'),
(833, 'Isle of Man', 'IM', 'IMN', 'Insel Man', 'Île de Man', 'Isola di Man'),
(834, 'Tanzania, United Republic of', 'TZ', 'TZA', 'Tansania, Vereinigte Republik', 'Tanzanie', 'Tanzania'),
(840, 'United States of America', 'US', 'USA', 'Vereinigte Staaten von Amerika', 'États-Unis', 'Stati Uniti'),
(850, 'Virgin Islands (U.S.)', 'VI', 'VIR', 'Amerikanische Jungferninseln', 'Îles Vierges des États-Unis', 'Isole Vergini americane'),
(854, 'Burkina Faso', 'BF', 'BFA', 'Burkina Faso', 'Burkina Faso', 'Burkina Faso'),
(858, 'Uruguay', 'UY', 'URY', 'Uruguay', 'Uruguay', 'Uruguay'),
(860, 'Uzbekistan', 'UZ', 'UZB', 'Usbekistan', 'Ouzbékistan', 'Uzbekistan'),
(862, 'Venezuela (Bolivarian Republic of)', 'VE', 'VEN', 'Venezuela', 'Venezuela', 'Venezuela'),
(876, 'Wallis and Futuna', 'WF', 'WLF', 'Wallis und Futuna', 'Wallis-et-Futuna', 'Wallis e Futuna'),
(882, 'Samoa', 'WS', 'WSM', 'Samoa', 'Samoa', 'Samoa'),
(887, 'Yemen', 'YE', 'YEM', 'Jemen', 'Yémen', 'Yemen'),
(894, 'Zambia', 'ZM', 'ZMB', 'Sambia', 'Zambie', 'Zambia'),
(895, 'Kosovo', 'XK', 'XKX', 'Kosovo', 'Kosovo', 'Kosovo'),
(896, 'Netherlands Antilles', 'AN', 'ANT', 'Niederländische Antillen', 'Antilles néerlandaises', 'Antille Olandesi');