export default {
    list: {
        user: 'list-user',
        tenant: 'list-tenant',
        pinboard: 'list-pinboard',
        product: 'list-product',
        request: 'list-request',
        audit: 'list-audit',
        building: 'list-building',
        address: 'list-address',
        unit: 'list-unit',
        propertyManager: 'list-property_manager',
        quarter: 'list-quarter',
        template: 'list-template',
        provider: 'list-provider',
        requestCategory: 'list-service_request_category',
    },
    view: {
        user: 'view-user',
        userSetting: 'view-user_setting',
        tenant: 'view-tenant',
        pinboard: 'view-pinboard',
        product: 'view-product',
        provider: 'view-provider',
        building: 'view-building',
        address: 'view-address',
        unit: 'view-unit',
        propertyManager: 'view-property_manager',
        quarter: 'view-quarter',
        settings: 'view-settings',
        template: 'view-template',
        requestCategory: 'view-service_request_category'
    },
    create: {
        comment: 'add-comment',
        pinboard: 'add-pinboard',
        user: 'add-user',
        tenant: 'add-tenant',
        pinboardToAnyLocation: 'add-located-pinboard',
        product: 'add-product',
        provider: 'add-provider',
        tenantRequest: 'add-request_tenant',
        serviceRequest: 'add-request_service',
        request: 'add-request',
        building: 'add-building',
        address: 'add-address',
        unit: 'add-unit',
        propertyManager: 'add-property_manager',
        quarter: 'add-quarter',
        template: 'add-template',
        requestCategory: 'add-service_request_category'
    },
    update: {
        requestTenant: 'edit-request_tenant',
        user: 'edit-user',
        userSettings: 'edit-user_setting',
        tenant: 'edit-tenant',
        comment: 'edit-comment',
        pinboard: 'edit-pinboard',
        product: 'edit-product',
        provider: 'edit-provider',
        request: 'edit-request',
        tenantRequest: 'edit-request_tenant',
        serviceRequest: 'edit-request_service',
        building: 'edit-building',
        address: 'edit-address',
        unit: 'edit-unit',
        propertyManager: 'edit-property_manager',
        quarter: 'edit-quarter',
        settings: 'edit-settings',
        template: 'edit-template',
        requestCategory: 'edit-service_request_category'
    },
    delete: {
        user: 'delete-user',
        tenant: 'delete-tenant',
        pinboard: 'delete-pinboard',
        product: 'delete-product',
        provider: 'delete-provider',
        request: 'delete-request',
        building: 'delete-building',
        address: 'delete-address',
        unit: 'delete-unit',
        propertyManager: 'delete-property_manager',
        quarter: 'delete-quarter',
        template: 'delete-template',
        requestCategory: 'delete-service_request_category'
    },
    publish: {
        pinboard: 'publish-pinboard',
        product: 'publish-product'
    },
    pin: {
        pinboard: 'pin-pinboard'
    },
    assign: {
        provider: 'assign-provider',
        request: 'assign-request',
        manager: 'assign-property_manager'
    }
}